env:
  global:
    - MOZ_HEADLESS=1
addons:
  firefox: latest

language: dart
sudo: required
dist: xenial
dart:
  - stable
  - beta
  - dev
before_script:
  - export DISPLAY=:0.0
script:
  - dart ./tool/travis.dart